name: BukkitPlatformPlugin
main: net.warcane.lugin.core.minecraft.BukkitPlatformPlugin
version: 1.0.0
author: sasuked
api-version: 1.13
depend: [ packetevents ]
softdepend: ["Vault", "PlaceholderAPI"]
