name: BukkitPlatformPlugin
main: io.github.minehollow.minecraft.BukkitPlatformPlugin
version: 1.0.0
author: sasuked
folia-supported: true
api-version: 1.13
depend: [ PlaceholderAPI, packetevents ]
soft-depend: [ Vault, TAB ]