name: Deploy plugins
on:
  workflow_dispatch:
    inputs:
      env:
        description: "Ambiente para deploy"
        type: choice
        required: true
        default: dev
        options: [dev, prod]

jobs:
  build-and-deploy:
    if: "!contains(github.event.head_commit.message, '[NO-CI]')"

    runs-on: ubuntu-latest
    name: Build and Deploy to Pterodactyl
    environment: ${{ github.event.inputs.env }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 1
      - name: Select environment
        id: environment
        run: |
          if [ "${{ github.event.inputs.env }}" == "prod" ]; then
            cp deploy.prod.json .pterodactyl-upload.json
            echo "PTERO_HOST=${{ vars.PROD_PANEL_URL }}" >> $GITHUB_ENV
            echo "PTERO_API_KEY=${{ secrets.PROD_API_KEY }}" >> $GITHUB_ENV
          else
            cp deploy.dev.json .pterodactyl-upload.json
            echo "PTERO_HOST=${{ vars.DEV_PANEL_URL }}" >> $GITHUB_ENV
            echo "PTERO_API_KEY=${{ secrets.DEV_API_KEY }}" >> $GITHUB_ENV
          fi
          cat .pterodactyl-upload.json
      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'zulu'
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4.4.3
        with:
          cache-read-only: false
          cache-write-only: false
          dependency-graph: generate-and-submit

      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            .gradle/caches
            .gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build -PluginUser=${{ secrets.LUGIN_USER }} -PluginPassword=${{ secrets.LUGIN_PASSWORD }}

      - name: Upload to Pterodactyl
        uses: rexlmanu/pterodactyl-upload-action@v2.5
        with:
          panel-host: ${{ env.PTERO_HOST }}
          api-key: ${{ env.PTERO_API_KEY }}
